### ISSUE TITLE
Compile error on core.rs

### ISSUE THREAD

**Issue by rcalvachi** [aws-samples/s3-fast-list#1]
I'm new to Rust and I keep on running into the error on core.rs line 84. It will not compile.

error[E0599]: no method named **as_str** found for type 64 in the current scope --> s3-fast-list/src/core.rs:84:52

84 | ...	let name = names.3.**as_str**();

help: there is a method as_ with a similar name

841	let name = names.3.as_();

![image](https://github.com/user-attachments/assets/2bc49777-38a3-4b97-883b-4555725c37e9)

Please review it. Thanks!

**Comment by daiyy** [comment]
Thanks for report this.

Reason for compile broken is dependency rhai API changed, I just pushed a fix cc6e193098440cfa635ea1973ece989c0e1704fc.

Please pull and build again.
